### ISSUE TITLE
looks for `routes_table_no_verb.csv` in path relative to current working directory

### ISSUE THREAD

**Issue by mbunkus** [tmlee/gitlab_ruby#1]
I've installed `gitlab_ruby` via `gem install gitlab_ruby`. Afterwards I tried using it, but that filed with the following error message:

```text
/usr/lib/ruby/2.4.0/csv.rb:1282:in `initialize': No such file or directory @ rb_sysopen - lib/gitlab_ruby/routes_table_no_verb.csv (Errno::ENOENT)
        from /usr/lib/ruby/2.4.0/csv.rb:1282:in `open'
        from /usr/lib/ruby/2.4.0/csv.rb:1282:in `open'
        from /usr/lib/ruby/2.4.0/csv.rb:1147:in `foreach'
        from /usr/lib/ruby/gems/2.4.0/gems/gitlab_ruby-0.2.1/lib/gitlab_ruby/query_chain.rb:18:in `generate_methods'
        from /usr/lib/ruby/gems/2.4.0/gems/gitlab_ruby-0.2.1/lib/gitlab_ruby.rb:17:in `<top (required)>'
        from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from ./bug_status.rb:7:in `<main>'
```

That file is present in the gem:

```shell
[0 mosu@sweet-chili /ftp/pub/rip/mkv/bugs] gem contents gitlab_ruby | grep csv
/usr/lib/ruby/gems/2.4.0/gems/gitlab_ruby-0.2.1/lib/gitlab_ruby/routes_table_no_verb.csv
```

It starts to work after I create `lib/gitlab_ruby` in the current directory and put a `routes_table_no_verb.csv` there, either as a symlink, or via wget'ting a copy from GitHub.

Conclusion: the file should be searched relative to `gitlab_ruby.rb`'s location or something like that, not realtive to the current working directory.

**Comment by bmedici** [comment]
Same here, witching lib then :(
